#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export PATH="$PATH:$(yarn global bin)" 
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH="$PATH:./node_modules/.bin"
export PATH="$HOME/.cabal/bin:$PATH"
source $HOME/config/zsh/plugins/asdf/asdf.sh
# source ~/.local/share/fonts/i_linux.sh

