#!/bin/env bash
# Arch linux xmonad setup script

#----------------- DO NOT EDIT THIS FILE INSTEAD EDIT 
red='\033[1;31m'
rset='\033[0m'
grn='\033[1;32m'
ylo='\033[1;33m'
blue='\033[1;34m'
#-----------------
#echo -e "$grn Sync and Update packages... $rset"
#yay -Syu
#clear
#-----------------
if [ -d ~/.sh ]; then
  echo -e "$blue  shell config detected. creating backup file and copying new config... $rset"
  cp -r ~/config/.sh/* ~/.sh/
else
  echo -e "$red copying shell config file... $rset"
  mkdir ~/.sh
  cp -r ~/config/.sh/* ~/.sh/
fi
#------------------
if [ -f ~/.sh/.xmobar.hs ]; then
  echo -e "$blue xmobar config detected. creating backup file and copying new config... $rset"
  cp ~/config/xmobar/.xmobar.hs ~/.sh/.xmobar.hs
else
  echo -e "$red copying xmobar config file... $rset"
  cp ~/config/xmobar/.xmobar.hs ~/.xmobar.hs
fi
#-----------------
if [ -d ~/.config/alacritty ]; then
  echo -e "$blue alacritty configs detected, backing up and copying new config...$rset"
   cp ~/config/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml 
else
  echo -e "$red installing alacritty configs... $rset"
  mkdir -p ~/.config/alacritty
  cp ~/config/alacritty/alacritty.yml ~/.config/alacritty/alacritty.yml
fi
#-----------------
if [ -f ~/.sh/.autostart.sh ]; then 
 echo -e "$blue autostart configs detected, backing up and copying new config... $rset"
 cp ~/config/autostart/.autostart.sh ~/.sh/.autostart.sh 
else
 echo -e "$red installing autostart configs... $rset"a
 cp ~/config/autostart/.autostart.sh ~/.autostart.sh 
fi
#-----------------
if [ -f ~/.zshrc ]; then
echo -e "$blue zsh configs detected, backing up and copying new config... $rset"
   cp  ~/config/zsh/.zshrc ~/.zshrc
else
  echo -e "$red Installing zsh configs... $rset"
  cp ~/config/zsh/.zshrc ~/.zshrc
fi
#-----------------
if [ -f ~/.sh/.picom.conf ]; then
echo -e "$blue picom configs detected, backing up and copying new config... $rset"
  cp  ~/config/picom/.picom.conf ~/.sh/.picom.conf
else
  echo -e "$red Installing zsh configs... $rset"
  cp ~/config/picom/.picom.conf ~/.picom.conf
fi
#-----------------
if [ -f ~/.config/spotifyd/spotifyd.conf ]; then
echo -e "$blue spotifyd configs detected, backing up and copying new config... $rset"
   cp  ~/config/spotifyd/spotifyd.conf ~/.config/spotifyd/spotifyd.conf
else
  echo -e "$red Installing spotifyd configs... $rset"
  cp ~/config/spotifyd/spotifyd.conf ~/.config/spotifyd/spotifyd.conf
fi
#-----------------
if [ -d ~/.xmonad/ ]; then
  echo -e "$blue xmonad configs detected, backing up and copying new config... $rset"
   cp ~/config/xmonad/xmonad.hs ~/.xmonad/xmonad.hs
else
  echo -e "$red Installing xmonad configs... $rset"
  mkdir ~/.xmonad/ && cp ~/config/xmonad/xmonad.hs ~/.xmonad/xmonad.hs
fi

sleep 1
function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

if [ -d ~/.xmonad ]; then
   xmonad --recompile  &
   xmonad --restart    &
   run nitrogen --restore &
   picom -b --animations --animation-window-mass 0.5 --animation-for-open-window fly-in --animation-stiffness 350 --animation-for-transient-window zoom --config $HOME/.sh/.picom.conf & # this is not normal picom
   ckb-next -b &
   run nm-applet &
   run pamac-tray &
   run xfce4-power-manager &
   run volumeicon &
   numlockx on &
   blueberry-tray &
   /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
   /usr/lib/xfce4/notifyd/xfce4-notifyd 
  fi

